version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: umami_umami_1
      APP_PORT: 3000

  umami:
    image: ghcr.io/umami-software/umami:postgresql-v2.4.1
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: $APP_SEED
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - ${APP_DATA_DIR}/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
